# environment.yml
# 还包含其他代码库的依赖项，比如 semantic-kitti-api
name: fyp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  # --- 其他 Conda 包可以列在这里 ---
  - pip:
      - fpsample
      - tqdm
      - PyYAML
      - vispy
      - --index-url https://download.pytorch.org/whl/cu126
      - torch
      - torchvision
      - torchaudio
